# Generated by Django 4.2.3 on 2023-07-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_medico_odontologo_pediatra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nuevoprofesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
    ]
